### ISSUE TITLE
ThinBox::clone() leaks Head if the iterator panics

### ISSUE THREAD

**Issue by adlerd** [CAD97/thin-dst#10]
A typo in `ThinBox::clone()` causes it to `drop_in_place` a `u8`, not a `Head`.

A test which demonstrates this is [here](https://github.com/adlerd/thin-dst/blob/ab089ed8b5d84f189468d1827e229d821db8f59b/tests/no_leaks.rs#L31).

I will follow up with a PR adding this test and fixing the issue, which are probably the best way to explain it, although I didn't give my full attention to make sure the fix is doing the right thing so someone should look closely :). I think a more complete fix would be to remove the `Head` from `InProgressThinBox` entirely as I'm not sure it really needs to be there.

**Comment by CAD97** [comment]
FWIW, this prompted me to go [clean up my panics over in slice-dst as well](https://github.com/CAD97/pointer-utils/pull/44).
