### ISSUE TITLE
ThinRef, ThinPtr

### ISSUE THREAD

**Issue by matklad** [CAD97/thin-dst#5]
When trying to remove double indirection in `rowan`'s `cursor` layer, I've noticed that I miss

```rust
pub struct ThinRef<'a, Head, SliceItem> {}

pub struct ThinPtr<Head, SliceItem> {}
```

Unlike `&ThinData` /  `*const ThinData`, these should be one pointer sized

**Comment by CAD97** [comment]
This is automatically handled by [a different approach to thin references](https://github.com/CAD97/pointer-utils) that I think is probably superior. If possible, could you do a doc/API review of those crates? My plan is to hopefully finish polishing up those crates then make this crate another part of that family.

These types should definitely be added, I agree. I'll get to them as soon as I have some time.

**Comment by matklad** [comment]
Yeah, I'll take a look. I've also just learned about triomphe, I wonder if it makes sense to swtich rowan to it, as we don't need weak refs, and ArcBorrow and ArcUnion seems to be exactly the things we need...

**Comment by matklad** [comment]
I've also noticed that, in general, there's quite a bit of friction with abstractions here (especially when we try to glue them into a union), so I've experimented with approach which basically flips the table and just use `* void` everywhere, without trying to invent more general abstractions: https://github.com/rust-analyzer/bonsai/blob/master/src/lib.rs

**Comment by CAD97** [comment]
Yeah, that's why I like erased. It makes working with `ErasedPtr` easier. I need to glue a `thin-dst` layer on top and make sure it works well.

I think somewhere in here we've a good improvement to LSTs.
